In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("C:\\Users\\HP\\Downloads\\nlp\\nlp-tutorials\\9_bag_of_words\\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam']=df['Category'].apply(lambda x: 1 if x=="spam" else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [11]:
df.shape

(5572, 3)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[0:4]

1357    U ned to convince him tht its not possible wit...
2209    URGENT!! Your 4* Costa Del Sol Holiday or £500...
3546                            Thank You meet you monday
2332                                   At home by the way
Name: Message, dtype: object

In [16]:
y_train[0:4]

1357    0
2209    1
3546    0
2332    0
Name: spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7760 sparse matrix of type '<class 'numpy.int64'>'
	with 59105 stored elements in Compressed Sparse Row format>

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
X_train_cv.shape

(4457, 7760)

In [25]:
v.get_feature_names_out()[1000:1050]

array(['answered', 'answerin', 'answering', 'answers', 'answr',
       'antelope', 'antha', 'anthony', 'anti', 'antibiotic', 'any',
       'anybody', 'anymore', 'anyone', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apartment', 'apeshit', 'aphex',
       'apnt', 'apo', 'apologetic', 'apologise', 'apologize', 'apology',
       'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaching'], dtype=object)

In [26]:
v.get_feature_names_out().shape

(7760,)

In [27]:
v.vocabulary_

{'ned': 4726,
 'to': 6938,
 'convince': 2022,
 'him': 3441,
 'tht': 6885,
 'its': 3773,
 'not': 4825,
 'possible': 5328,
 'witot': 7566,
 'hurting': 3564,
 'his': 3446,
 'feeling': 2817,
 'the': 6818,
 'main': 4328,
 'urgent': 7208,
 'your': 7722,
 'costa': 2045,
 'del': 2249,
 'sol': 6297,
 'holiday': 3473,
 'or': 4976,
 '5000': 548,
 'await': 1180,
 'collection': 1917,
 'call': 1629,
 '09050090044': 173,
 'now': 4840,
 'toclaim': 6943,
 'sae': 5878,
 'tc': 6727,
 'pobox334': 5275,
 'stockport': 6486,
 'sk38xh': 6211,
 'cost': 2044,
 '50': 546,
 'pm': 5267,
 'max10mins': 4400,
 'thank': 6805,
 'you': 7718,
 'meet': 4430,
 'monday': 4570,
 'at': 1134,
 'home': 3477,
 'by': 1614,
 'way': 7421,
 'dunno': 2498,
 'da': 2167,
 'next': 4766,
 'show': 6135,
 'aft': 871,
 'is': 3753,
 '850': 695,
 'toa': 6939,
 'payoh': 5131,
 'got': 3206,
 '650': 595,
 'height': 3401,
 'of': 4893,
 'confidence': 1978,
 'all': 933,
 'aeronautics': 858,
 'professors': 5442,
 'wer': 7472,
 'calld': 1635,
 'amp':

In [29]:
X_train_np=X_train_cv.toarray()
X_train_np[0]  #first email 

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
np.where(X_train_np[0]!=0) #first email

(array([2022, 2817, 3441, 3446, 3564, 3773, 4328, 4726, 4825, 5328, 6818,
        6885, 6938, 7566], dtype=int64),)

In [32]:
X_train[:4][1357]

'U ned to convince him tht its not possible witot hurting his feeling its the main'

In [33]:
X_train_np[0][2022]

1

In [34]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [35]:
X_test_cv=v.transform(X_test)

In [37]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.95      0.91      0.93       135

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [38]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

# above process using pipeline

In [39]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [40]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [41]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.95      0.91      0.93       135

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

